// AUTO-GENERATED by scripts/extract-catalog-images.mjs — do not edit manually
// Generated: 2026-09-20T15:24:34.506Z

export interface ProductImageEntry {
  catalogNumber:   number;
  productId:       string;
  sku:             string;
  productName:     string;
  pdfPage:         number;
  imagePath:       string;
  width:           number;
  height:          number;
  extractionMethod:string;
  fileSize:        number;
}

export const productImageManifest: ProductImageEntry[] = [
  {
    "catalogNumber": 1,
    "productId": "prod-001",
    "sku": "LK-001",
    "productName": "Chaqueta Denim con Parches",
    "pdfPage": 3,
    "imagePath": "/images/products/luale-001-chaqueta-denim-con-parches.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 39342
  },
  {
    "catalogNumber": 2,
    "productId": "prod-002",
    "sku": "LK-002",
    "productName": "Set 3 Piezas León",
    "pdfPage": 4,
    "imagePath": "/images/products/luale-002-set-3-piezas-leon.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 66446
  },
  {
    "catalogNumber": 3,
    "productId": "prod-003",
    "sku": "LK-003",
    "productName": "Pantalones Jogger con Lazo",
    "pdfPage": 5,
    "imagePath": "/images/products/luale-003-pantalones-jogger-con-lazo.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 20158
  },
  {
    "catalogNumber": 4,
    "productId": "prod-004",
    "sku": "LK-004",
    "productName": "Joggers Cargo Estampados",
    "pdfPage": 6,
    "imagePath": "/images/products/luale-004-joggers-cargo-estampados.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 70026
  },
  {
    "catalogNumber": 5,
    "productId": "prod-005",
    "sku": "LK-005",
    "productName": "Set Leggings Básicos",
    "pdfPage": 7,
    "imagePath": "/images/products/luale-005-set-leggings-basicos.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 50166
  },
  {
    "catalogNumber": 6,
    "productId": "prod-013",
    "sku": "LK-013",
    "productName": "Medias con Olán Tonos Neutros",
    "pdfPage": 8,
    "imagePath": "/images/products/luale-006-medias-con-olan-tonos-neutros.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 44530
  },
  {
    "catalogNumber": 7,
    "productId": "prod-014",
    "sku": "LK-014",
    "productName": "Medias con Lazo Colores Pastel",
    "pdfPage": 9,
    "imagePath": "/images/products/luale-007-medias-con-lazo-colores-pastel.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 49414
  },
  {
    "catalogNumber": 8,
    "productId": "prod-015",
    "sku": "LK-015",
    "productName": "Medias Básicas",
    "pdfPage": 10,
    "imagePath": "/images/products/luale-008-medias-basicas.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 15338
  },
  {
    "catalogNumber": 9,
    "productId": "prod-016",
    "sku": "LK-016",
    "productName": "Medias Smile Tonos Neutros",
    "pdfPage": 11,
    "imagePath": "/images/products/luale-009-medias-smile-tonos-neutros.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 59514
  },
  {
    "catalogNumber": 10,
    "productId": "prod-006",
    "sku": "LK-006",
    "productName": "Pijamas Enterizas Estampadas",
    "pdfPage": 12,
    "imagePath": "/images/products/luale-010-pijamas-enterizas-estampadas.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 82914
  },
  {
    "catalogNumber": 11,
    "productId": "prod-017",
    "sku": "LK-017",
    "productName": "Pijamas 2 Piezas Dulces",
    "pdfPage": 13,
    "imagePath": "/images/products/luale-011-pijamas-2-piezas-dulces.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 55834
  },
  {
    "catalogNumber": 12,
    "productId": "prod-018",
    "sku": "LK-018",
    "productName": "Pijamas Enterizas Transportes",
    "pdfPage": 14,
    "imagePath": "/images/products/luale-012-pijamas-enterizas-transportes.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 82002
  },
  {
    "catalogNumber": 13,
    "productId": "prod-019",
    "sku": "LK-019",
    "productName": "Pijamas 2 Piezas Dinosaurios",
    "pdfPage": 15,
    "imagePath": "/images/products/luale-013-pijamas-2-piezas-dinosaurios.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 71418
  },
  {
    "catalogNumber": 14,
    "productId": "prod-020",
    "sku": "LK-020",
    "productName": "Sets Leggings Blanco y Negro",
    "pdfPage": 16,
    "imagePath": "/images/products/luale-014-sets-leggings-blanco-y-negro.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 69764
  },
  {
    "catalogNumber": 15,
    "productId": "prod-021",
    "sku": "LK-021",
    "productName": "Vestido Gris con Blusa",
    "pdfPage": 17,
    "imagePath": "/images/products/luale-015-vestido-gris-con-blusa.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 84232
  },
  {
    "catalogNumber": 16,
    "productId": "prod-022",
    "sku": "LK-022",
    "productName": "Rompers Florales Modelo 1",
    "pdfPage": 18,
    "imagePath": "/images/products/luale-016-rompers-florales-modelo-1.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 64054
  },
  {
    "catalogNumber": 17,
    "productId": "prod-023",
    "sku": "LK-023",
    "productName": "Set Rayas con Cerezas",
    "pdfPage": 19,
    "imagePath": "/images/products/luale-017-set-rayas-con-cerezas.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 73746
  },
  {
    "catalogNumber": 18,
    "productId": "prod-024",
    "sku": "LK-024",
    "productName": "Rompers Florales Modelo 2",
    "pdfPage": 20,
    "imagePath": "/images/products/luale-018-rompers-florales-modelo-2.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 86010
  },
  {
    "catalogNumber": 19,
    "productId": "prod-025",
    "sku": "LK-025",
    "productName": "Overol Denim con Camiseta Bebé",
    "pdfPage": 21,
    "imagePath": "/images/products/luale-019-overol-denim-con-camiseta-bebe.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 39022
  },
  {
    "catalogNumber": 20,
    "productId": "prod-026",
    "sku": "LK-026",
    "productName": "Overol Denim con Camiseta Infantil",
    "pdfPage": 22,
    "imagePath": "/images/products/luale-020-overol-denim-con-camiseta-infantil.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 36588
  },
  {
    "catalogNumber": 21,
    "productId": "prod-027",
    "sku": "LK-027",
    "productName": "Sets Tejidos de Verano",
    "pdfPage": 23,
    "imagePath": "/images/products/luale-021-sets-tejidos-de-verano.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 90666
  },
  {
    "catalogNumber": 22,
    "productId": "prod-028",
    "sku": "LK-028",
    "productName": "Conjunto Waffle Marrón",
    "pdfPage": 24,
    "imagePath": "/images/products/luale-022-conjunto-waffle-marron.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 93950
  },
  {
    "catalogNumber": 23,
    "productId": "prod-029",
    "sku": "LK-029",
    "productName": "Conjunto Waffle Verde",
    "pdfPage": 25,
    "imagePath": "/images/products/luale-023-conjunto-waffle-verde.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 102152
  },
  {
    "catalogNumber": 24,
    "productId": "prod-030",
    "sku": "LK-030",
    "productName": "Conjunto Animalitos",
    "pdfPage": 26,
    "imagePath": "/images/products/luale-024-conjunto-animalitos.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 51166
  },
  {
    "catalogNumber": 25,
    "productId": "prod-031",
    "sku": "LK-031",
    "productName": "Conjuntos Básicos Osito",
    "pdfPage": 27,
    "imagePath": "/images/products/luale-025-conjuntos-basicos-osito.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 41950
  },
  {
    "catalogNumber": 26,
    "productId": "prod-032",
    "sku": "LK-032",
    "productName": "Conjunto Mama",
    "pdfPage": 28,
    "imagePath": "/images/products/luale-026-conjunto-mama.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 48980
  },
  {
    "catalogNumber": 27,
    "productId": "prod-007",
    "sku": "LK-007",
    "productName": "Vestido Polo Rosa",
    "pdfPage": 29,
    "imagePath": "/images/products/luale-027-vestido-polo-rosa.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 16214
  },
  {
    "catalogNumber": 28,
    "productId": "prod-033",
    "sku": "LK-033",
    "productName": "Vestido de Lunares Blanco y Negro",
    "pdfPage": 30,
    "imagePath": "/images/products/luale-028-vestido-de-lunares-blanco-y-negro.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 71910
  },
  {
    "catalogNumber": 29,
    "productId": "prod-008",
    "sku": "LK-008",
    "productName": "Conjunto Deportivo Oliva",
    "pdfPage": 31,
    "imagePath": "/images/products/luale-029-conjunto-deportivo-oliva.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 49216
  },
  {
    "catalogNumber": 30,
    "productId": "prod-034",
    "sku": "LK-034",
    "productName": "Medias Altas con Lazo",
    "pdfPage": 32,
    "imagePath": "/images/products/luale-030-medias-altas-con-lazo.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 24422
  },
  {
    "catalogNumber": 31,
    "productId": "prod-035",
    "sku": "LK-035",
    "productName": "Set Floral Naranja",
    "pdfPage": 35,
    "imagePath": "/images/products/luale-031-set-floral-naranja.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 22426
  },
  {
    "catalogNumber": 32,
    "productId": "prod-009",
    "sku": "LK-009",
    "productName": "Set Floral Rosa",
    "pdfPage": 36,
    "imagePath": "/images/products/luale-032-set-floral-rosa.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 25184
  },
  {
    "catalogNumber": 33,
    "productId": "prod-036",
    "sku": "LK-036",
    "productName": "Set Sunset Studios",
    "pdfPage": 37,
    "imagePath": "/images/products/luale-033-set-sunset-studios.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 37314
  },
  {
    "catalogNumber": 34,
    "productId": "prod-037",
    "sku": "LK-037",
    "productName": "Set Capri Italy",
    "pdfPage": 38,
    "imagePath": "/images/products/luale-034-set-capri-italy.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 17548
  },
  {
    "catalogNumber": 35,
    "productId": "prod-038",
    "sku": "LK-038",
    "productName": "Conjunto Tie-Dye",
    "pdfPage": 39,
    "imagePath": "/images/products/luale-035-conjunto-tie-dye.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 29004
  },
  {
    "catalogNumber": 36,
    "productId": "prod-039",
    "sku": "LK-039",
    "productName": "Set Polo Oakland Celeste",
    "pdfPage": 40,
    "imagePath": "/images/products/luale-036-set-polo-oakland-celeste.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 18508
  },
  {
    "catalogNumber": 37,
    "productId": "prod-010",
    "sku": "LK-010",
    "productName": "Set Polo Oakland Azul",
    "pdfPage": 41,
    "imagePath": "/images/products/luale-037-set-polo-oakland-azul.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 17100
  },
  {
    "catalogNumber": 38,
    "productId": "prod-040",
    "sku": "LK-040",
    "productName": "Hoodie Blanco + Jogger Gris",
    "pdfPage": 42,
    "imagePath": "/images/products/luale-038-hoodie-blanco-jogger-gris.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 16484
  },
  {
    "catalogNumber": 39,
    "productId": "prod-041",
    "sku": "LK-041",
    "productName": "Hoodie Crema + Jogger Vino",
    "pdfPage": 43,
    "imagePath": "/images/products/luale-039-hoodie-crema-jogger-vino.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 14144
  },
  {
    "catalogNumber": 40,
    "productId": "prod-042",
    "sku": "LK-042",
    "productName": "Set Camiseta + Pantalón Verde",
    "pdfPage": 44,
    "imagePath": "/images/products/luale-040-set-camiseta-pantalon-verde.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 19820
  },
  {
    "catalogNumber": 41,
    "productId": "prod-043",
    "sku": "LK-043",
    "productName": "Vestido Camiseta Parches Crema",
    "pdfPage": 45,
    "imagePath": "/images/products/luale-041-vestido-camiseta-parches-crema.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 24934
  },
  {
    "catalogNumber": 42,
    "productId": "prod-044",
    "sku": "LK-044",
    "productName": "Set Beach Vibes Rosa",
    "pdfPage": 46,
    "imagePath": "/images/products/luale-042-set-beach-vibes-rosa.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 18682
  },
  {
    "catalogNumber": 43,
    "productId": "prod-011",
    "sku": "LK-011",
    "productName": "Vestido Camiseta Parches Fucsia",
    "pdfPage": 47,
    "imagePath": "/images/products/luale-043-vestido-camiseta-parches-fucsia.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 16016
  },
  {
    "catalogNumber": 44,
    "productId": "prod-012",
    "sku": "LK-012",
    "productName": "Set AMORE Coral",
    "pdfPage": 48,
    "imagePath": "/images/products/luale-044-set-amore-coral.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 15966
  },
  {
    "catalogNumber": 45,
    "productId": "prod-045",
    "sku": "LK-045",
    "productName": "Set AMORE Gris",
    "pdfPage": 49,
    "imagePath": "/images/products/luale-045-set-amore-gris.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 17362
  },
  {
    "catalogNumber": 46,
    "productId": "prod-046",
    "sku": "LK-046",
    "productName": "Sets Waffle Oso Dinosaurio",
    "pdfPage": 33,
    "imagePath": "/images/products/luale-046-sets-waffle-oso-dinosaurio.webp",
    "width": 880,
    "height": 642,
    "extractionMethod": "page-crop",
    "fileSize": 106354
  }
];

export const imageByProductId: Record<string, string> =
  Object.fromEntries(productImageManifest.map(e => [e.productId, e.imagePath]));

export const imageByCatalogNumber: Record<number, string> =
  Object.fromEntries(productImageManifest.map(e => [e.catalogNumber, e.imagePath]));
