/**
 * Mappers between Supabase snake_case DB rows and frontend camelCase types.
 * All Supabase repositories import from here — no raw DB types leak into components.
 *
 * DbRow is a loose type for raw Supabase query results. Proper typed versions
 * will be generated by `supabase gen types typescript` once a remote project is connected.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type DbRow = Record<string, any>;

import type {
  Category,
  Product,
  ProductImageRecord,
  ProductVariant,
  ProductPurchaseOption,
  Customer,
  Order,
  OrderItem,
  Expense,
  StoreSettings,
  InventoryMovement,
  MerchandiseEntry,
  MerchandiseEntryItem,
} from '@/lib/types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? '';

function toPublicUrl(storagePath: string): string {
  if (!storagePath) return '';
  if (storagePath.startsWith('/') || storagePath.startsWith('http')) {
    return storagePath;
  }
  return `${SUPABASE_URL}/storage/v1/object/public/product-images/${storagePath}`;
}

// ── Categories ────────────────────────────────────────────────

export function mapCategory(row: DbRow): Category {
  return {
    id:          row.id,
    name:        row.name,
    slug:        row.slug,
    description: row.description ?? undefined,
    order:       row.sort_order,
    active:      row.active,
    createdAt:   row.created_at,
  };
}

// ── Products ──────────────────────────────────────────────────

export function mapProduct(row: DbRow): Product {
  const variants: ProductVariant[] = (row.product_variants ?? []).map(mapVariant);
  const purchaseOptions: ProductPurchaseOption[] = (row.product_purchase_options ?? []).map(mapPurchaseOption);

  const sortedRawImages: DbRow[] = (row.product_images ?? [])
    .slice()
    .sort((a: DbRow, b: DbRow) => (a.position ?? 0) - (b.position ?? 0));

  const productImages: ProductImageRecord[] = sortedRawImages.map((img: DbRow) => ({
    id:          String(img.id),
    storagePath: String(img.storage_path ?? ''),
    publicUrl:   toPublicUrl(String(img.storage_path ?? '')),
    altText:     String(img.alt_text ?? ''),
    position:    Number(img.position ?? 0),
    isPrimary:   Boolean(img.is_primary),
    width:       img.width ?? undefined,
    height:      img.height ?? undefined,
    fileSize:    img.file_size ?? undefined,
  }));

  const images: string[] = productImages.map((img) => img.publicUrl);

  const categoryIds: string[] = (row.product_categories ?? []).map(
    (pc: DbRow) => pc.category_id
  );

  return {
    id:                   row.id,
    name:                 row.name,
    slug:                 row.slug,
    sku:                  row.sku,
    description:          row.description ?? '',
    price:                purchaseOptions.length > 0 ? purchaseOptions[0].price : 0,
    cost:                 0, // cost is private — not fetched in public queries
    categoryIds,
    variants,
    images,
    productImages,
    status:               mapAvailability(row.manual_availability),
    featured:             row.featured,
    featuredOrder:        row.featured_order ?? null,
    isNew:                row.is_new,
    visible:              row.status === 'active',
    archivedAt:           row.archived_at ?? undefined,
    garmentType:          row.garment_type ?? '',
    tags:                 row.tags ?? [],
    createdAt:            row.created_at,
    updatedAt:            row.updated_at,
    catalogNumber:        row.catalog_number ?? undefined,
    purchaseOptions:      purchaseOptions.length > 0 ? purchaseOptions : undefined,
    inventoryConfigured:  row.inventory_configured,
    lowStockThreshold:    row.low_stock_threshold ?? undefined,
    sizeNote:             row.size_note ?? undefined,
  };
}

export function mapVariant(row: DbRow): ProductVariant {
  return {
    id:    row.id,
    size:  row.size,
    color: row.color ?? undefined,
    stock: row.inventory_levels?.quantity_on_hand ?? 0,
    sku:   row.sku ?? undefined,
  };
}

export function mapPurchaseOption(row: DbRow): ProductPurchaseOption {
  return {
    id:                String(row.id),
    label:             String(row.label),
    price:             Number(row.price),
    sortOrder:         Number(row.sort_order ?? 0),
    unitDescription:   row.unit_description ?? undefined,
    quantityIncluded:  row.quantity_included ?? undefined,
  };
}

function mapAvailability(val: string): Product['status'] {
  const map: Record<string, Product['status']> = {
    automatic:    'consult',       // legacy: treat same as consult
    available:    'available',
    low_stock:    'low_stock',
    out_of_stock: 'out_of_stock',
    coming_soon:  'coming_soon',
    consult:      'consult',       // "Consultar disponibilidad" — distinct from available
  };
  return map[val] ?? 'consult';
}

// ── Customers ─────────────────────────────────────────────────

export function mapCustomer(row: DbRow): Customer {
  return {
    id:        row.id,
    name:      row.name,
    phone:     row.phone,
    city:      row.city ?? '',
    address:   row.address ?? undefined,
    notes:     row.notes ?? undefined,
    orderIds:  (row.orders ?? []).map((o: DbRow) => o.id),
    createdAt: row.created_at,
  };
}

// ── Orders ────────────────────────────────────────────────────

export function mapOrder(row: DbRow): Order {
  return {
    id:            row.id,
    customerId:    row.customer_id ?? '',
    customerName:  row.customer_name_snapshot ?? '',
    items:         (row.order_items ?? []).map(mapOrderItem),
    total:         Number(row.total),
    paymentMethod: (row.order_payments?.[0]?.payment_method ?? 'other') as Order['paymentMethod'],
    status:        row.status as Order['status'],
    paymentStatus: row.payment_status as Order['paymentStatus'],
    notes:         row.notes ?? undefined,
    date:          row.created_at,
    createdAt:     row.created_at,
  };
}

export function mapOrderItem(row: DbRow): OrderItem {
  return {
    productId:    row.product_id ?? '',
    variantId:    row.variant_id ?? '',
    productName:  row.product_name_snapshot,
    variantLabel: [row.size_snapshot, row.color_snapshot].filter(Boolean).join(' — '),
    quantity:     row.quantity,
    unitPrice:    Number(row.unit_price),
    totalPrice:   Number(row.line_total),
  };
}

// ── Expenses ──────────────────────────────────────────────────

export function mapExpense(row: DbRow): Expense {
  return {
    id:            row.id,
    date:          row.expense_date,
    category:      (row.expense_categories?.slug ?? 'other') as Expense['category'],
    description:   row.description,
    amount:        Number(row.amount),
    paymentMethod: row.payment_method as Expense['paymentMethod'],
    receiptUrl:    row.receipt_path ?? undefined,
    notes:         row.notes ?? undefined,
    createdAt:     row.created_at,
  };
}

// ── Store settings ────────────────────────────────────────────

export function mapSettings(row: DbRow): StoreSettings {
  return {
    storeName:          row.store_name,
    tagline:            row.tagline,
    secondaryTagline:   row.tagline,
    whatsapp:           row.whatsapp_display,
    whatsappLink:       row.whatsapp_number,
    instagram:          row.instagram_url ? `@${row.instagram_url.split('/').pop()}` : '',
    location:           row.location,
    deliveryInfo:       row.delivery_text,
    shippingInfo:       row.shipping_text,
    currency:           row.currency,
    currencySymbol:     row.currency_symbol,
    domain:             row.site_domain,
    aboutText:          row.about_text ?? '',
  };
}

// ── Inventory ─────────────────────────────────────────────────

export function mapInventoryMovement(row: DbRow): InventoryMovement {
  const typeMap: Record<string, InventoryMovement['type']> = {
    merchandise_entry:   'entry',
    sale:                'exit',
    return:              'entry',
    adjustment_in:       'adjustment',
    adjustment_out:      'adjustment',
    cancellation_restore:'entry',
  };
  return {
    id:         row.id,
    productId:  row.variant?.product_id ?? '',
    variantId:  row.variant_id,
    type:       typeMap[row.movement_type] ?? 'adjustment',
    quantity:   Math.abs(row.quantity_delta),
    reason:     row.notes ?? '',
    reference:  row.reference_id ?? undefined,
    date:       row.created_at.split('T')[0],
    createdAt:  row.created_at,
  };
}

export function mapMerchandiseEntry(row: DbRow): MerchandiseEntry {
  const items: MerchandiseEntryItem[] = (row.merchandise_entry_items ?? []).map(
    (it: DbRow): MerchandiseEntryItem => ({
      productId:  it.product_variants?.product_id ?? '',
      variantId:  it.variant_id,
      quantity:   it.quantity,
      unitCost:   Number(it.unit_cost),
    })
  );
  const totalCost = items.reduce((s, it) => s + it.unitCost * it.quantity, 0)
    + Number(row.additional_costs ?? 0);

  return {
    id:              row.id,
    date:            row.entry_date,
    reference:       row.reference,
    supplier:        row.suppliers?.name ?? undefined,
    items,
    additionalCosts: Number(row.additional_costs ?? 0),
    totalCost,
    notes:           row.notes ?? undefined,
    createdAt:       row.created_at,
  };
}
